server:
  port: 26338
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tigerconfig/tiggermetricsconfig
          search-paths: config-repo
          username: tigerconfig
          password: a3643212
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: user
    password: pwd
    virtual-host: /
eureka:
  client:
    serviceUrl:
      defaultZone: http://luhost:Test_12345@localhost:26335/eureka/
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: bus-refresh