version: '3'
services:

  account:
    image: tiggermetrics/account-service
    ports:
      - 26336:26336
    restart: always

  statistics:
    image: tiggermetrics/statistics-service
    ports:
      - 26337:26337
    restart: always

  turbine:
    image: tiggermetrics/turbine
    ports:
      - 26341:26341
    restart: always

  gateway:
    image: tiggermetrics/gateway
    ports:
      - 26339:26339
    restart: always