server:
  port: 26339
spring:
  application:
    name: gateway
zuul:
  routes:
    config:
      path: /config/**
      serviceId: config
    accout-service:
      path: /accout-service/**
      serviceId: accout-service
    statistics-service:
      path: /statistics-service/**
      serviceId: statistics-service
  retryable: true
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 10000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 2 # 同一服务不同实例的重试次数
  MaxAutoRetries: 2 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # 熔断超时时长：6000ms
eureka:
  client:
    serviceUrl:
      defaultZone: http://luhost:Test_12345@localhost:26335/eureka/