server:
  port: 26335
spring:
  security:
    user:
      name: luhost
      password: Test_12345
  application:
    name: registry
eureka:
  instance:
    hostname: localhost
  server:
    # 测试时关闭自我保护机制，保证不可用服务及时踢出
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://luhost:Test_12345@${eureka.instance.hostname}:${server.port}/eureka/