server:
  port: 26337
spring:
  application:
    name: statistics-service
  cloud:
    config:
      name: rate
      profile: config
    bus:
      trace:
        enabled: true
  rabbitmq:
    host:
    port:
    username:
    password:
management:
  security:
    enabled: false