server:
  port: 26337
spring:
  application:
    name: statistics-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: user
    password: pwd
    virtual-host: /
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: bus-refresh