server:
  port: 26336
spring:
  application:
    name: accout-service
  zipkin:
    base-url: http://localhost:26340
    sleuth:
      sampler:
        percentage: 1.0

mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://luhost:Test_12345@localhost:26335/eureka/