server:
  port: 26336
spring:
  application:
    name: accout-service

mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://luhost:Test_12345@localhost:26335/eureka/